### ISSUE TITLE
undefined method `downcase' for nil:NilClass

### ISSUE THREAD

**Issue by kidbrax** [dev-sec/cis-docker-benchmark#32]
When executing this profile, I get this:

```
/usr/local/bundle/gems/inspec-1.23.0/lib/resources/docker.rb:32:in `block (2 levels) in <class:DockerContainerFilter>': undefined method `downcase' for nil:NilClass (NoMethodError)
	from /usr/local/bundle/gems/inspec-1.23.0/lib/utils/filter.rb:63:in `instance_eval'
	from /usr/local/bundle/gems/inspec-1.23.0/lib/utils/filter.rb:63:in `block in where'
	from /usr/local/bundle/gems/inspec-1.23.0/lib/utils/filter.rb:63:in `each'
	from /usr/local/bundle/gems/inspec-1.23.0/lib/utils/filter.rb:63:in `find_all'
	from /usr/local/bundle/gems/inspec-1.23.0/lib/utils/filter.rb:63:in `where'
	from /usr/local/bundle/gems/inspec-1.23.0/lib/resources/docker.rb:32:in `block in <class:DockerContainerFilter>'
	from /usr/local/bundle/gems/inspec-1.23.0/lib/utils/filter.rb:204:in `block in create_connector'
	from /usr/local/bundle/gems/inspec-1.23.0/lib/utils/filter.rb:178:in `call'
	from /usr/local/bundle/gems/inspec-1.23.0/lib/utils/filter.rb:178:in `block (2 levels) in connect'
	from cis-docker-benchmark-master/controls/container_images.rb:50:in `block in load_with_context'
	from /usr/local/bundle/gems/inspec-1.23.0/lib/inspec/rule.rb:51:in `instance_eval'
	from /usr/local/bundle/gems/inspec-1.23.0/lib/inspec/rule.rb:51:in `initialize'
	from /usr/local/bundle/gems/inspec-1.23.0/lib/inspec/control_eval_context.rb:71:in `new'
	from /usr/local/bundle/gems/inspec-1.23.0/lib/inspec/control_eval_context.rb:71:in `block (2 levels) in create'
	from cis-docker-benchmark-master/controls/container_images.rb:37:in `load_with_context'
	from /usr/local/bundle/gems/inspec-1.23.0/lib/inspec/profile_context.rb:146:in `instance_eval'
	from /usr/local/bundle/gems/inspec-1.23.0/lib/inspec/profile_context.rb:146:in `load_with_context'
	from /usr/local/bundle/gems/inspec-1.23.0/lib/inspec/profile_context.rb:130:in `load_control_file'
	from /usr/local/bundle/gems/inspec-1.23.0/lib/inspec/profile.rb:149:in `block in collect_tests'
	from /usr/local/bundle/gems/inspec-1.23.0/lib/inspec/profile.rb:146:in `each'
	from /usr/local/bundle/gems/inspec-1.23.0/lib/inspec/profile.rb:146:in `collect_tests'
	from /usr/local/bundle/gems/inspec-1.23.0/lib/inspec/dependencies/dependency_set.rb:65:in `block in each'
	from /usr/local/bundle/gems/inspec-1.23.0/lib/inspec/dependencies/dependency_set.rb:64:in `each'
	from /usr/local/bundle/gems/inspec-1.23.0/lib/inspec/dependencies/dependency_set.rb:64:in `each'
	from /usr/local/bundle/gems/inspec-1.23.0/lib/inspec/profile.rb:144:in `collect_tests'
	from /usr/local/bundle/gems/inspec-1.23.0/lib/inspec/runner.rb:90:in `block in load'
	from /usr/local/bundle/gems/inspec-1.23.0/lib/inspec/runner.rb:79:in `each'
	from /usr/local/bundle/gems/inspec-1.23.0/lib/inspec/runner.rb:79:in `load'
	from /usr/local/bundle/gems/inspec-1.23.0/lib/inspec/runner.rb:100:in `run'
	from /usr/local/bundle/gems/inspec-1.23.0/lib/inspec/base_cli.rb:83:in `run_tests'
	from /usr/local/bundle/gems/inspec-1.23.0/lib/inspec/cli.rb:166:in `exec'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /usr/local/bundle/gems/inspec-1.23.0/bin/inspec:12:in `<top (required)>'
	from /usr/local/bundle/bin/inspec:17:in `load'
	from /usr/local/bundle/bin/inspec:17:in `<main>'
```

**Comment by chris-rock** [comment]
Can you open the inspec shell via `inspec shell` and run `docker.containers.running?.ids`?

**Comment by chris-rock** [comment]
Seems to be a bug in inspec

**Comment by kidbrax** [comment]
Sure, this is what I get:

```
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

You are currently running on:

    OS platform:  amazon
    OS family:  amazon
    OS release: 2016.09

inspec> docker
=> Docker Host
inspec> docker.containers
=> #<Inspec::Resources::DockerContainerFilter:0x0000000233f480 @containers=[{}]>
inspec> docker.containers.running?
=> #<Inspec::Resources::DockerContainerFilter:0x0000000221d610> with status downcase start_with? "up"
inspec> docker.containers.running?.ids
=> []
```

**Comment by jdel** [comment]
I am running into the same issue with a docker container I built based on chef/inspec where I just add the docker client:

> Dockerfile
```
FROM chef/inspec:1.23.0

RUN apk add --update docker \
 && rm -rf /usr/bin/docker-* /usr/bin/dockerd \
 && rm -rf /var/cache/apk/*
``` 

I am running the container and bind mount my docker socket and get the same error as described: 

```
docker run -ti --rm --name inspec -v /var/run/docker.sock:/var/run/docker.sock:ro jdel/inspec exec https://github.com/dev-sec/cis-docker-benchmark
[2017-05-03T15:41:40+00:00] WARN: URL target https://github.com/dev-sec/cis-docker-benchmark transformed to https://github.com/dev-sec/cis-docker-benchmark/archive/master.tar.gz. Consider using the git fetcher
/usr/local/bundle/gems/inspec-1.23.0/lib/resources/docker.rb:32:in `block (2 levels) in <class:DockerContainerFilter>': undefined method `downcase' for nil:NilClass (NoMethodError)
[...]
```

Below is the result from `docker run -ti --rm --name inspec -v /var/run/docker.sock:/var/run/docker.sock:ro jdel/inspec shell` with the troubleshooting commands you requested:
I have a different output than @kidbrax

```
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

You are currently running on:

    OS platform:  alpine
    OS family:  alpine
    OS release: 3.4.6

inspec> docker
=> Docker Host
inspec> docker.containers
=> #<Inspec::Resources::DockerContainerFilter:0x005648f99aa298 @containers=[{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}]>
inspec> docker.containers.running?
NoMethodError: undefined method `downcase' for nil:NilClass
from /usr/local/bundle/gems/inspec-1.23.0/lib/resources/docker.rb:32:in `block (2 levels) in <class:DockerContainerFilter>'
inspec> docker.containers.running?.ids?
NoMethodError: undefined method `downcase' for nil:NilClass
from /usr/local/bundle/gems/inspec-1.23.0/lib/resources/docker.rb:32:in `block (2 levels) in <class:DockerContainerFilter>'
```

If I run `docker run -ti --rm --name inspec -v /var/run/docker.sock:/var/run/docker.sock:ro --entrypoint /bin/sh jdel/inspec` I can then do a `docker ps` and see my containers running (4 of them).

To me this looks like a bug in `docker.containers.running?`

I have tried inspec 1.21, 1.22, and 1.23 with no success.

**Comment by chris-rock** [comment]
@jdel Thank you, I agree that this looks like a bug in `docker.containers.running?` Can you please open an issue in https://github.com/chef/inspec/issues ?

**Comment by kidbrax** [comment]
I have submitted an issue to inspec, https://github.com/chef/inspec/issues/1788

**Comment by chris-rock** [comment]
Based on the inspec implementation, our baseline works only with Docker 1.13+

**Comment by chris-rock** [comment]
I opened PR #35 to document the required docker version in our Readme. Since InSpec is keeping track of that, we can lower the required version if InSpec supports more. I am going to close this issue now. Please reopen if it required
